import { NgModule } from '@angular/core';
import {
  MatButtonModule,
  MatSidenavModule,
  MatButtonToggleModule,
  MatExpansionModule,
  MatDialogModule,
  MatCardModule,
  MatSelectModule,
  MatIconModule,
  MatSnackBarModule,
  MatInputModule,
  MatListModule,
  MatMenuModule,
  MatToolbarModule,
  MatDividerModule,
  MatGridListModule,
  MatFormFieldModule,
  MatTabsModule,
  MatTooltipModule,
  MatChipsModule,
  MatTreeModule,
  MatDatepickerModule,
  MatNativeDateModule,
  MatCheckboxModule,
  MatProgressSpinnerModule
} from '@angular/material';
import { CdkTreeModule } from "@angular/cdk/tree";

@NgModule({
  imports: [
    MatButtonModule,
    MatSidenavModule,
    MatButtonToggleModule,
    MatExpansionModule,
    MatDialogModule,
    MatCardModule,
    MatSelectModule,
    MatIconModule,
    MatSnackBarModule,
    MatInputModule,
    MatListModule,
    MatMenuModule,
    MatToolbarModule,
    MatDividerModule,
    MatGridListModule,
    MatFormFieldModule,
    MatTabsModule,
    MatTooltipModule,
    MatChipsModule,
    MatDatepickerModule,
    MatNativeDateModule,
    MatCheckboxModule,
    MatProgressSpinnerModule,
    MatTreeModule,
    CdkTreeModule
  ],
  exports: [
    MatButtonModule,
    MatSidenavModule,
    MatButtonToggleModule,
    MatExpansionModule,
    MatDialogModule,
    MatCardModule,
    MatSelectModule,
    MatIconModule,
    MatSnackBarModule,
    MatInputModule,
    MatListModule,
    MatMenuModule,
    MatToolbarModule,
    MatDividerModule,
    MatGridListModule,
    MatFormFieldModule,
    MatTabsModule,
    MatTooltipModule,
    MatChipsModule,
    MatDatepickerModule,
    MatNativeDateModule,
    MatCheckboxModule,
    MatProgressSpinnerModule,
    MatTreeModule,
    CdkTreeModule
  ]
})
export class MaterialModule {}
