image: docker:stable

before_script:
   - docker info
   - docker login -u synthsym -p cEdPd7s5APX9ztKWhkt2 $CI_REGISTRY

api:
  stage: build
  variables:
    IMAGE_TAG: $CI_REGISTRY_IMAGE/api:$CI_COMMIT_REF_SLUG
  script:
    - docker build --pull -t $IMAGE_TAG backend/
    - docker push $IMAGE_TAG

frontend:
  stage: build
  variables:
    BUILD_IMAGE_TAG: $CI_REGISTRY_IMAGE/frontend-build:$CI_COMMIT_REF_SLUG
    IMAGE_TAG: $CI_REGISTRY_IMAGE/frontend:$CI_COMMIT_REF_SLUG
  script:
    - docker build --pull -t $BUILD_IMAGE_TAG -f frontend/build.Dockerfile frontend/
    - docker push $BUILD_IMAGE_TAG
    - docker build --pull -t $IMAGE_TAG frontend/
    - docker push $IMAGE_TAG

