frontend:
  image: registry.gitlab.com/synthsym/follyengine/frontend-build:lts-slim
  script:
    - cd frontend
    - yarn install --frozen-lockfile --non-interactive
    - yarn run build
  stage: build
  artifacts:
    name: "$CI_JOB_NAME"
    paths:
      - frontend/dist/
