version: '3'

services:
  api:
    build: ./backend
    depends_on:
      - db
    env_file: .env
    environment:
      - DJANGO_SETTINGS_MODULE=follyengine.settings.prod

  db:
    image: postgres
    restart: always
    env_file: .env
    volumes:
      - db:/var/lib/postgresql/data

  web:
    image: nginx
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api

volumes:
  db:
