version: '3'

services:
  api:
    image: registry.gitlab.com/synthsym/follyengine/api:latest
    depends_on:
      - db
    deploy:
      replicas: 1

  db:
    image: postgres
    volumes:
      - db:/var/lib/postgresql/data
    deploy:
      replicas: 1

  web:
    image: registry.gitlab.com/synthsym/follyengine/frontend:latest
    depends_on:
      - api
    deploy:
      replicas: 1

volumes:
  db:
