version: '3'

services:
  api:
    volumes:
      - ./backend/follyengine:/app/follyengine
    environment:
      - DJANGO_SETTINGS_MODULE=follyengine.settings.dev
    entrypoint: ["python", "manage.py"]
    command: ["runserver", "0.0.0.0:8000"]

  db:
    environment:
      - POSTGRES_USER="follyengine"
      - POSTGRES_PASSWORD="cameo-Knot-walt-Joint-meyer"

  web:
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./follyengine.dev.conf:/etc/nginx/conf.d/follyengine.dev.conf
