version: '3'

services:
  api:
    volumes:
      - ./backend/follyengine:/app/follyengine
    environment:
      - DJANGO_SETTINGS_MODULE=follyengine.settings.dev
    entrypoint: ["python", "manage.py"]
    command: ["runserver", "0.0.0.0:8000"]

  web:
    volumes:
      - ./follyengine.dev.conf:/etc/nginx/conf.d/follyengine.dev.conf
