version: '3'

services:
  api:
    build: ./backend
    depends_on:
      - db

  db:
    image: postgres
    restart: always
    volumes:
      - db:/var/lib/postgresql/data

  web:
    image: nginx
    depends_on:
      - api

volumes:
  db:
