version: '3'

services:
  api:
    build: ./backend
    depends_on:
      - db
    env_file: .env
    environment:
      - DATABASE_URI=mysql+pymysql://root:${MYSQL_ROOT_PASSWORD}@db/${MYSQL_DATABASE}

  db:
    image: mariadb
    restart: always
    env_file: .env
    volumes:
      - db:/var/lib/mysql

  web:
    image: nginx
    ports:
      - 8000:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api

volumes:
  db:
