version: '3'

services:
  api:
    build: backend/
    volumes:
      - ./backend/follyengine:/app/follyengine
    environment:
      - DJANGO_SETTINGS_MODULE=follyengine.settings.dev
    entrypoint: ["python", "manage.py"]
    command: ["runserver", "0.0.0.0:8000"]

  db:
    environment:
      - POSTGRES_USER="follyengine"
      - POSTGRES_PASSWORD="cameo-Knot-walt-Joint-meyer"

  web:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./frontend/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./frontend/follyengine.dev.conf:/etc/nginx/conf.d/follyengine.dev.conf
