version: '3.7'

services:
  api:
    build: backend/
    volumes:
      - ./backend/follyengine:/app/follyengine
    entrypoint: ["python", "manage.py"]
    command: ["runserver", "0.0.0.0:8000"]

  web:
    image: nginx
    volumes:
      - ./frontend/nginx.conf:/etc/nginx/nginx.conf:ro

secrets:
  db_user:
    file: compose/db_user
  db_password:
    file: compose/db_password

configs:
  django_settings:
    file: /backend/follyengine/settings/dev.py
  nginx_settings:
    file: /frontend/follyengine.dev.conf
