version: '3'

services:
  api:
    build: ./backend
    depends_on:
      - db

  db:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "cameo-Knot-walt-Joint-meyer"
      MYSQL_DATABASE: "follyengine"

  web:
    image: nginx
    ports:
      - 8000:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api
