import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';
import { MatButtonModule,
	MatSidenavModule,
	MatButtonToggleModule,
	MatExpansionModule,
	MatDialogModule,
	MatCardModule,
	MatSelectModule,
	MatIconModule,
	MatSnackBarModule,
	MatInputModule,
	MatListModule,
	MatMenuModule,
	MatToolbarModule,
	MatDividerModule,
	MatGridListModule,
	MatFormFieldModule,
	MatTabsModule,
	MatTooltipModule,
	MatChipsModule,
	MatDatepickerModule,
	MatNativeDateModule,
	MatCheckboxModule,
	MatProgressSpinnerModule,
} from '@angular/material';

@NgModule({
	imports: [
		MatButtonModule,
		MatSidenavModule,
		MatButtonToggleModule,
		MatExpansionModule,
		MatDialogModule,
		MatCardModule,
		MatSelectModule,
		MatIconModule,
		MatSnackBarModule,
		MatInputModule,
		MatListModule,
		MatMenuModule,
		MatToolbarModule,
		MatDividerModule,
		MatGridListModule,
		MatFormFieldModule,
		MatTabsModule,
		MatTooltipModule,
		MatChipsModule,
		MatDatepickerModule,
		MatNativeDateModule,
		MatCheckboxModule,
		MatProgressSpinnerModule,
	],
	exports: [
		MatButtonModule,
		MatSidenavModule,
		MatButtonToggleModule,
		MatExpansionModule,
		MatDialogModule,
		MatCardModule,
		MatSelectModule,
		MatIconModule,
		MatSnackBarModule,
		MatInputModule,
		MatListModule,
		MatMenuModule,
		MatToolbarModule,
		MatDividerModule,
		MatGridListModule,
		MatFormFieldModule,
		MatTabsModule,
		MatTooltipModule,
		MatChipsModule,
		MatDatepickerModule,
		MatNativeDateModule,
		MatCheckboxModule,
		MatProgressSpinnerModule,
	]
})

export class MaterialModule{}
