# Generated by Django 2.1.4 on 2018-12-20 04:05

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import ulid2


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.UUIDField(default=ulid2.generate_ulid_as_uuid, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
                ('slug', models.SlugField(allow_unicode=True, max_length=64)),
                ('description', models.TextField(blank=True)),
                ('attributes', django.contrib.postgres.fields.jsonb.JSONField(default=list)),
            ],
        ),
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.UUIDField(default=ulid2.generate_ulid_as_uuid, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
                ('slug', models.SlugField(allow_unicode=True, max_length=64)),
                ('description', models.TextField(blank=True)),
                ('components', models.ManyToManyField(related_name='components', to='folly_api.Component')),
            ],
        ),
        migrations.CreateModel(
            name='Flow',
            fields=[
                ('id', models.UUIDField(default=ulid2.generate_ulid_as_uuid, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
                ('data', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=ulid2.generate_ulid_as_uuid, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=64)),
                ('slug', models.SlugField(allow_unicode=True, max_length=64)),
                ('description', models.TextField(blank=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='flow',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flows', to='folly_api.Project'),
        ),
        migrations.AddField(
            model_name='entity',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entities', to='folly_api.Project'),
        ),
        migrations.AddField(
            model_name='component',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='folly_api.Project'),
        ),
        migrations.AlterUniqueTogether(
            name='flow',
            unique_together={('name', 'project')},
        ),
        migrations.AlterUniqueTogether(
            name='entity',
            unique_together={('name', 'project')},
        ),
        migrations.AlterUniqueTogether(
            name='component',
            unique_together={('name', 'project')},
        ),
    ]
