# Generated by Django 2.1.1 on 2018-09-13 02:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('folly_api', '0002_auto_20180911_0451'),
        ('folly_api', '0002_auto_20180911_0351'),
    ]

    operations = [
    ]
