# Generated by Django 2.1.1 on 2018-09-14 02:59

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('folly_api', '0004_auto_20180914_0257'), ('folly_api', '0005_auto_20180914_0257')]

    dependencies = [
        ('folly_api', '0003_merge_20180913_0227'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attribute',
            name='component',
        ),
        migrations.AddField(
            model_name='component',
            name='attributes',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='component',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='entity',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.DeleteModel(
            name='Attribute',
        ),
    ]
