# Generated by Django 2.1.1 on 2018-09-19 13:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('folly_api', '0004_auto_20180914_0257_squashed_0005_auto_20180914_0257'),
    ]

    operations = [
        migrations.AddField(
            model_name='flow',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='flows', to='folly_api.Project'),
            preserve_default=False,
        ),
    ]
