# Generated by Django 2.1.1 on 2018-09-21 04:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('folly_api', '0006_auto_20180920_0607'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='component',
            unique_together={('name', 'project')},
        ),
        migrations.AlterUniqueTogether(
            name='entity',
            unique_together={('name', 'project')},
        ),
        migrations.AlterUniqueTogether(
            name='flow',
            unique_together={('name', 'project')},
        ),
    ]
