# Generated by Django 2.1.1 on 2018-10-09 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('folly_api', '0007_auto_20180921_0414'),
    ]

    operations = [
        migrations.AddField(
            model_name='component',
            name='slug',
            field=models.SlugField(allow_unicode=True, default='default', max_length=64),
            preserve_default=False,
        ),
    ]
