# Generated by Django 2.1.1 on 2018-10-06 00:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('folly_api', '0008_asset'), ('folly_api', '0009_auto_20181006_0001')]

    dependencies = [
        ('folly_api', '0007_auto_20180921_0414'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('file', models.FileField(upload_to='assets/')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='folly_api.Project')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='asset',
            unique_together={('name', 'project')},
        ),
    ]
